apiVersion: v1
kind: PersistentVolume
metadata:
  name: seafile-mariadb
  namespace: seafile
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/gluster/global/seafile/db
