apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-mariadb-data-pv
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: seafile-mariadb-data-pv