apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-data
  namespace: seafile
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/gluster/global/seafile/mariadb