apiVersion: v1
kind: PersistentVolume
metadata:
  name: seafile-data-pv
  namespace: seafile
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/gluster/global/seafile/server
