apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-data-pvc
  namespace: seafile
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: seafile-data-pv