apiVersion: apps/v1
kind: Deployment
metadata:
  name: seafile
  namespace: seafile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seafile
  template:
    metadata:
      labels:
        app: seafile
    spec:
      containers:
        - name: seafile
          #        image: seafileltd/seafile-mc:9.0.10
          #        image: seafileltd/seafile-mc:11.0-latest
          # seafile-pro-mc:11.0-latest
          image: seafileltd/seafile-mc:11.0.13-arm
          env:
            #- name: DB_ROOT_PASSWD
            #  value: "db_dev" #db's password
            #- name: TIME_ZONE
            #  value: "Europe/Berlin"
            #- name: SEAFILE_ADMIN_EMAIL
            #  value: "admin@seafile.com" #admin email
            #- name: SEAFILE_ADMIN_PASSWORD
            #  value: "admin_password" #admin password
            #- name: SEAFILE_SERVER_HOSTNAME
            #  value: "you_seafile_domain" #hostname
            - name: DB_HOST
              value: "mariadb"
            - name: DB_ROOT_PASSWD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MARIADB_ROOT_PASSWORD
            - name: TIME_ZONE
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: TIME_ZONE
            - name: SEAFILE_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: seafile-secret
                  key: SEAFILE_ADMIN_EMAIL
            - name: SEAFILE_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: seafile-secret
                  key: SEAFILE_ADMIN_PASSWORD
            - name: SEAFILE_SERVER_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: seafile-secret
                  key: SEAFILE_SERVER_HOSTNAME
            - name: SEAFILE_SERVER_LETSENCRYPT
              value: "false"
          ports:
            - containerPort: 80
          #        - containerPort: 443
          #          name:  seafile-secure
          volumeMounts:
            - name: seafile-data
              mountPath: /shared
      volumes:
        - name: seafile-data
          persistentVolumeClaim:
            claimName: seafile-data
      restartPolicy: Always
      # to get image from protected repository
      imagePullSecrets:
        - name: regcred