apiVersion: v1
kind: PersistentVolume
metadata:
  name: seafile-data
  namespace: seafile
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/gluster/global/seafile/server
