apiVersion: v1
kind: PersistentVolume
metadata:
  name: seahub-avatars-pv
  namespace: seafile
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/gluster/global/seafile/avatars
