apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectlife-api-connector
  namespace: mosquitto
  labels:
    app: connectlife-api-connector
  annotations:
    argocd-image-updater.argoproj.io/image-list: kallewasnowicz/connectlife-api-connector
    argocd-image-updater.argoproj.io/update-strategy: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connectlife-api-connector
  template:
    metadata:
      labels:
        app: connectlife-api-connector
    spec:
      containers:
      - name: connectlife-api-connector
        image: kallewasnowicz/connectlife-api-connector:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: CONNECTLIFE_LOGIN
          valueFrom:
            secretKeyRef:
              name: connectlife-api-connector-secret
              key: CONNECTLIFE_LOGIN
        - name: CONNECTLIFE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: connectlife-api-connector-secret
              key: CONNECTLIFE_PASSWORD
        - name: LOG_LEVEL
          value: "info"
        - name: MQTT_HOST
          valueFrom:
            secretKeyRef:
              name: connectlife-api-connector-secret
              key: MQTT_HOST
        - name: MQTT_USER
          valueFrom:
            secretKeyRef:
              name: connectlife-api-connector-secret
              key: MQTT_USER
        - name: MQTT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: connectlife-api-connector-secret
              key: MQTT_PASSWORD
        - name: MQTT_PORT
          value: "1883"
        - name: MQTT_SSL
          value: "false"
        - name: DEVICES_CONFIG
          value: '{"117":{"t_work_mode":["fan only","heat","cool","dry","auto"],"t_fan_speed":{"0":"auto","5":"super low","6":"low","7":"medium","8":"high","9":"super high"},"t_swing_direction":["straight","right","both sides","swing","left"],"t_swing_angle":{"0":"swing","2":"bottom 1/6 ","3":"bottom 2/6","4":"bottom 3/6","5":"top 4/6","6":"top 5/6","7":"top 6/6"}}}'
        command: ["/bin/ash", "-c", "/usr/bin/supervisord -c /home/app/docker-files/supervisord.conf"]
