apiVersion: v1
kind: Service
metadata:
  name: connectlife-api-connector
  namespace: connectlife-api-connector
spec:
  selector:
    app: connectlife-api-connector
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8000
  type: ClusterIP
