apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng
  namespace: searxng
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: searxng-pv