---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: admin-token
  namespace: vaultwarden
spec:
  encryptedData:
    admin-token: AgCZrjdv1y5A+HO0Umot+MLOn4yG/Tew5RkbfkvfH9bKVWdxykU9h26uylp2M2vSYtx7NmsfFsRvvNtMSCp5VErKTxEGwmu2jwwpKvOaa4zVNbnqZkxbG1VzStUJAa4Vs5FHoHP18/q9PW1PTJpl/RIvHQOEjbS/tMcNM58W5CJcZuN0bZRlscDPNkJWgJV8tcChmuHIiHIUrKy4avZJcKi5/ibzPjlZmorKeK+M2F4SBVa5ZasyxaBo7QJtO6V64euhrxLbq0HaUIzJcHfq7ioF+/HIp6DhZFpLX4BXcHSNZ2pVusyBjztfNSoh+m6aIawtQJMAg+27mexzeH9n8tRyNY/Ff2vzK2MYILMf/83WBhbALbbtRFiRecl4X0p4MZ6mLBYTE1aP5AXTgGLaQrDB3bNVAp+os6m45vNPH6uozxCTCNR1Jh5519Hesakngo3EH8c3Ti0whIaek4yTVbtFkAYIAtk/igCGJ+0hhHwsJalu5MuEGLD5rNOmqb4GB7jAyqnsuY0wC3g+8F/U4Ks5G6hiUiBuiGssrSZmgOI0/SVv7XgqM1M+9sLGCxt7R7rx6jOfdtpD4q+xcNd4nnGCsaau8z+thaOAh9leNvd5MnZE5rxFLbOViDBuk8E279BvP8BZcH+kc39+GDu8poBEFb7DZ04Wadj+z2vddLybbLqmQQyd2HG8CoLS9+oJgEMAEIncJv3Ey6eIWqfeLy89J0q7clw=
  template:
    metadata:
      creationTimestamp: null
      name: admin-token
      namespace: vaultwarden
    type: Opaque
