---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vaultwarden-admin-token
  namespace: vaultwarden
spec:
  encryptedData:
    admin-token: AgAeNmjOgR/phd9BWFKtUnxFTC/AH2kgoCv7ep6jsTme2/b4lHeo9JKhcDU12vSiiGTDmz5uc86jGGNjEePx9YoqcYllcgQkLT2oileuFMjnxE2V46kAvW5VsYkpiMr6b1Wed7Y5ERAQ9udmg1kOmggtRrCAKXtFQXbaXsR6j3EDDRz700LlBPrWVJqptZjrs4RYoclhY4ZoCm0JrJ+uSfGHb0iUcaRr88LlLkCkfkmoIaagqfYUNTkRMHP5X3H2sATxIsPOweQ1RxXoJ0ff9yovmVoshVq1Kz6qeqG8G9UsGWjOl1xDdAJX9RdyWpf+UPZZcs5p/9Gp/hAq1yKypRlbJEPRDDHS66kz0VqXdwTwdTFffJGzDIYy54/VvjZrpxcZeBKmj6XkyBRbajMllzKJgP+ty9klnQuBpJJ4qjSTvECs/pH4yIJAXkfoUzmwvHp5mquSl4aO97RpZJ9L7tndH22R8KkhTDqo20D0IKTMD5azblLb2g3Fo6DjB1HVRxbS224XoAtqyVZwt+P4HHau06wD8mJSqOgZES8/oQ6reySTE4lZh2t4FErUMgbLoQccBxz7FpS+LdUefATg9/sn9IYlyuft+UPBQ72cOHON52r6Ff4BOviQ5c9w9mFCSwfg2AGdk0OC2zmlzGyKIRudRyD4X7Q8SrSOkagkCKgvBJ7oZrZjNf7gD1JjImHH+M6agfDwuDGbFYLrAomDIvF/Wkzpp5s=
  template:
    metadata:
      creationTimestamp: null
      name: vaultwarden-admin-token
      namespace: vaultwarden
    type: Opaque
