---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vaultwarden-admin-token
  namespace: vaultwarden
spec:
  encryptedData:
    admin-token: AgA0ORUXElN7uKykmkzunMVv5NOie+bLcogmmIIMYTCCL2f5E63jqbf1NWjS1rUDkktcuPtdLwYrjYN/IAdje0kZTxz4xOozWAsGMc/ScaYBKDXcCZMG/url8J8cJWHoiTmRL3x0iMt+DbFDLrKbdqIZivO9r5dPybdSF87rBPxDvr75qhi7h6yrLNfrZOdu6L7HFBbIqT+vVcIYQE7BjXJ6I7FeyWxmcpXyoZJEK849yObT5c+UJQW0DghRavPnO6ycI7avQEv5VCCbrmXgYF+2Te/vNfCZxE/ogxqJJ4TH1hfBUucSAtYb8Ag8GrTHHJQxMoLJiQGilUxLe6MfHMR4cDB5pSwUc+nyBA1SdSkc/KjxRcD8bHfwrNxYVhP1lsYqHN8vyHWDHMBiibFesVgCbUB0GFiVpBnc9qX6YXPq9VBEPFjcq12aDqXmfoxEd7QFQqvJ8Z4KlbmysQB0TwMr69/vtj//Gnl+UEbXTdRokGDMo85fLWK4G+AbVIrOPeFfLeAJH6LJssi1lgZvInjM/3qpyGtopUIZRAYR9EChFkEKWECvL9SfFQ8YVnfQtbQGlZhHBUwbvOz+dpzdVjlkQa+Ag50NHqvNNdUp/SVX/ti1KS0V+e93jOgWETqds3SFY7otv5DYBOAGugaJ3m9XcErcPPIXsHrOH4kK/aCgcLkM1c01e6lQrB+jiNQ0kuE0RDJfmxbhULrW5UYMZvu86ks2cU4=
  template:
    metadata:
      creationTimestamp: null
      name: vaultwarden-admin-token
      namespace: vaultwarden
    type: Opaque
