---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: vaultwarden
spec:
  encryptedData:
    api-token: AgBYctI9Cu3xy5dL4Grs0vXmBo1ptr6Z8iPsph3xu9di44A5wnECP0QtKuf63mPTCCZROaunV2PW1UFYlDwPWdivwd98PjVlmDYstf8DPpTYgsCvN9lJbsrIbPbdbUh3q7lAdXJiCx+bYwpD58M5SDg4TKHtsWWQIDv8BW4QyJ7A0/JaMZc8NN6Fptma4PibGKGxqMFP3ogYC4u+LtD4UDUCNohHP1FnZJafSkrSYtv0ueXlOFydQFvazzNLA+JmgrjXV4lD/M3Xzzaua9DM4/+iaFSGjSSugBpJWKZlnJwNkYqi5rmpKxtKAwNLvLGUW4QVgLA99YEKrKcp6SNq92RAqi6BG6pjwu+FArk/vKzy/u7VxKkXS2sg/napi0GWSHLZhf2RIymOp87Q7O79qOtYrh4r7xNm89pq4CYjHGWtOGbNfjW9xh9lRHjw2XEpM9Jjpikw1T0I403DMOnLIE72AULaCdeOpjImsEDo6unsmgSm6vDYOulGkKIH0zI2ItNcOnWTQYbk+cFM7E1iUygyOXLkQMdpKWDbdmc5Ymr9ZBwig5lA8O9naOARkMEAUWXHKc3jaDRCPfak3Iml9pNKDpklAwsxF33YFmkx34I7zf0ptf4qYxRLhD10aIFZh66/KNlwoBrZTURwzaqcEJSE0VfjyeyXHq3pBNUq9AkokyN6Q6hmBRsHWjd75G8kobW3nSy5X7HGNkkpX6eBMbjL3eLJ0oM4bQJW/U6mBr7aK0GvaJtIQKGV
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: vaultwarden
    type: Opaque
