---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: vaultwarden
spec:
  encryptedData:
    api-token: AgA5my8Q8njcMKirA/QTYHYBbNv/TqDkGP7Ml75eW6u1Mkx5M/byQ4pnqjYvVQK8ed+Vj0JHrymRH+bw0WDGGH27EHE6KVe2v7pTQZBoCGPMt+dOgXPoMbggdj+VnZQUI4hudi+8ngBQ3KgcF26Yfq6QpTocekCuIqjaOAe5NJh9ZHlPswr7Xv9jqMwhCs60mq1yLDZ3NIAC76ESjeag0NFemu2cgEerNi2M9JdX/naRiWVD3ei/AncGiqtSnGIbo1r9xGsKMAZV7fTf7revBdlyzKIho9M6LnXE2G+UN75j7gVvQHSUmuH2yQdRmW8hYGoFDHMlyhYxfMIw5cbYgY01gxvOs/0MmJ6KcnoUkLvDoOILS0L/RfvJxUqDaMjCJ6wlL9E08tS6558qnmH68M1tEKV6z+o7e4iGYOw2l920mDwVuvuzHNX1t5JjYapFLuegreWD7NVJ/xa9QcaNxHiP0cZNMBtXLGulX1I0Xj329irF22v/4pOA5O7kf5OCrdBgjVVIkSL6E+mLVwZmW6nQOHD8kTZpUPhRHkbAZxE9tRn/JKUQFU7AXVzlDTfyDQK5YQX6Soh54OjDEPQgQ8/RMljih9f20WEbF+cs0t9ib8TCY3N+cjIHueOzIalFuDuxV2BUm0hjDjRx30Rcov8mvJJIe3q5mnlwLdJJ4l7dLdHr/W4Q8njcGBiteL5UfVL8NgVdWrNhUf7T9mCniUdkKrcPLuw/3fU5FMTWix+YXysT/1+vz+ab
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: vaultwarden
    type: Opaque
