---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: argocd
spec:
  encryptedData:
    api-token: AgBEg3HxJ3g/OOOqP6cqHnDZJWzzOQR6KTg/XhNL5gp0pvVbjuWyvV235GcG7yG9dsEMmkWTolHiTQZ3P5IBdzRYWePB8hnB6ELiS626tLLFnR6C/9wkfCrm4uHwPIh5E0+5lrqo0tQ0qRS5A7HlOXN4yYr2l02VP05omz/h9LB7AzWLcwoKIRZ9Va/sTMW6BWwGILVrfXze2yyxRaeNjeeIj0tPo8hklW+tTqIEkll2YbUY9b/67wlT0nSpREgFgPYOuOLQELUENZitvQrH2wTJP6Rmb+HYOqPtAEYk+xQWc8TNpMVPwig4xllA8WQUZXpQmlmtckKX7ynReeByyrieuxhwSKnRw3gYpxXKWLwsC6OAZRu7yeQp98QTMTtmp/c0q2Kv62Ziz03qrw9xiyBa/2QI2C233fWaamzUKM1ds6exbrS7ZTCNPpkqpIS4J+0COJ4haitFPgjmVJbKKco5zkZ74zgwQGn+ZlOSVrNKX6VDTSGeSaI+9rZBUOgZlQNEfJkKQw+JfVcHtv27BDLgyzQ9q/FC/lu6kALOzSUplRZXkDB0NMVvckpIyDNqtCU8gmjmbOXAOQLOCso4nasnDaMaGZqQzx06bdYP8JmN8Wwi5nrHGiq3tLxuIoktCHzSceiJ0upBNoSgKF399PmuZfb/07iJ/uC1hEuxIUZB034T9oHG0Pu2wUKzUFrK0KH0AXvdp7M1owpxzLlUH08tMMxmmjNJ5PiQhBcYj2sa/dteNc35GIAs
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: argocd
    type: Opaque
