apiVersion: v1
kind: PersistentVolume
metadata:
  name: zigbee2mqtt-pv
  namespace: adguard
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/kube/zigbee2mqtt
