apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-pv
  namespace: homeassistant
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/kube/homeassistant
