---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: homeassistant
spec:
  encryptedData:
    api-token: AgB22YsnHLJn6YzwmUkvTsyDm0rCRpFGT3GovJxuW6xTwZ5dZt+VUyL9qZBJbplTU8DY5O1Hz6GiQo3mECwo2/A2McVCXxfDKi8c03rLQsOaXtjr4R1vz9rTiOrLezcWn8WRX/zKqsOcl3PYLwH5Q1oTQHmvaU97D7QCwqO3Cyz4pN0KffwApEJ0mlcMqZmifWC3lUiB8kBFuwtTm5QYcLoUbNcPxu9KOCpeuHRIslWTbBZ4xNl1qybySfEzY+Dkq2fgYePAPWM/kfW6d8E2EG6hBKQHBDt9ZuTUrEVr52Q/D5lhKTPhcaqW7rCpB5ag56ydYqILv/rwOmwzwnTdLqHPdg3tzVWb28NyJc8kuSxcUYhBoKXyCK4gfDQ79BK6e2zth8Y1CdVP9KhH4QfZIyoI0c9bnNYDfpB234plCvo7YUOeR0FVCNO8oVdRflqlQHXlONmlcarNTJWS5pF+OmRLBKuZeLgXyh5pFZDdeinaliQiv9kB5MeiEAnqmWgENeZpYjdpfiD/vjWfQgShUbuYS0i8M00eXA2lvPQZFQX4KzZqz/mAhg9zV+oNXL+1uNENoZJr1kK42W8vcNjXcV/psoG89o3UCeHyDyYYiY/0q52zEHKWa8gPwY7TOpd01VAQWZX1NgLEzAvoazl9RXFIRMJ5SHfUvZyXzLmJHxdcY3TSrr+1HatNPwfufrkTmHRY1wXOQ8iKIJyHOSYktGYrlv99j48jcofh/ENRrcnUPAqVEGz5oRTk
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: homeassistant
    type: Opaque
