---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: homeassistant
spec:
  encryptedData:
    api-token: AgDMjqA6bDi7AVuqvRA7jcAy8J4isDMymv6bi7VNcZTl+9sNyV9qyXdv7ebC9vYT3+iUI1joKxJYzZtuzkCrmZFJ6PDTEElopYI54izFonDd333EUkx1Gr9DP2vEsWiqtsT9bHU9GAEvjCFDo8shQG7BfNHHdvrEODEsRII/gK6AIGlOVgxjmzCVrWt4GieWA829r0joys7fxVXrWR0Ty+ZDVSXJdvc1R+6uJ23AIUBK5zbln8OqqG/rTgC3UPLoeaUFe0CfStRLPQReEGsRFTOO1BDjnzhWUBdlgA1bI5sV7SFlBV27XXCSr++GMIrKFel3v09i+4J+3yddJlJB3DtK3/24Ixcnife/fPXw7LHKm49eqsUDKBzoYcYmk5m84ulSGS1CtWWn5eQeo0jqaKs9HueMtWMqtuGI0jHHSpRdPJV6Jys1SRE7zgVOGVHrH9dtqoM4KBjwPwnv5KUm5RO1sPXDkWIx43cKOe/lkmfN8YfRnNje7mDHWRn/pBmfL2G6fpOx1WuxRNJYKI2T7N6wGERMYVtp8NywiIEVDJKcqn0M3dsZVmTMjIeHbdZFF8p9hnhT9gX0dN2aSSFDnbh2kwxlfiqqH5V5Mv8eEom1nkDxTfgOhsW15w7U6MQ7b+JxVIn7BlTHZkNrtoW9e38oUtDyW5x4ELMv7hnNNKnDPkAUI4mrQ8kUMicAJgqu778s27/G5b0prYwYAVwJa/PNVvCu6tevGvwzH3p2x9obLKJJayFlcyky
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: homeassistant
    type: Opaque
