apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-pv
  namespace: mosquitto
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/gluster/global/mosquitto
