apiVersion: v1
kind: PersistentVolume
metadata:
  name: seafile-data-pv
  namespace: seafile
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/gluster/global/seafile/data