---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: seafile
spec:
  encryptedData:
    api-token: AgBVdBaQrKKZirCl/JApVtXdkqOh5ufxs/zB8zf21atKVenzRSXj2FNdQjX9UUs+lg+vhdBKV5lBeNx0yTJK4V/SEHTq+vkJu5dm4wtpf9KBEgsiLhQva+wC8dUXLxs/Kbc8gK3T57WhFps9Fi75dFPtixCnVsZhLgWtsY2kRTfyLTFAmStHJYhngf9NYNp1F0Xf1q7Ey6tr3USn97oK9J2rBrSGwwZBclD7w+zMjY+B2W4rQyni+/Ja+VZT6551/fzVwN/WKHoRzAsuEN4iUldQ4Vkfv7nSAWgdEXPAAhv2SUMFpRPGL+NBqFQQQKRpLmuOBtrbuD1qJPh+7M7xzRGEIXGRnvs0pL+TSb1wkCWdHql7Qh8PLDAAf2yiS3bA8FUOdgarbAfWeeKV1vyqM6paHB7N4vWMZH2Xi+xEDo2ICh8Lcy1pDGI+x2HP7n41lqxt8upK1qcarHyd+/LDg1cG1leerqvk8UolWRR+g5ffXRsw71eUa30eWQBtQpJyyTPBapwPETdLs5eao9EzXh7/Y7W925uSSaPP+81a2DrmptA0DKW66tqCFJajARPs9a03QK41vrKwOQDFRKXUuN5Vjc6Y3V0nPKBz9k5BH9QnKCt49yjTKEzN+3+8kRDtbcl3QOc/I65U5VHuFNRAn8rP5E2UgRYdXNxEppgqvNZXaPfGeqVrsQ6ZkmffXgem6Z52kpypIMd/sKXVNnZA3QjTCsKjY8IhS/yrS3QbqJpEDMPgRKVN8qG8
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: seafile
    type: Opaque
