apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baikal-config-pvc
  namespace: baikal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: baikal-config-pv
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baikal-data-pvc
  namespace: baikal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: baikal-data-pv
  storageClassName: ""