---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: argocd
spec:
  encryptedData:
    api-token: AgCo1yLgCuoAmX8+TfbZ49aYbi7AuaondxCuJNmjDALZ2sLzpJgdDZgefF959AZ/CAjEYXh1jRVi4zJ2DMqRVh4pvJpNut4aQH8om3FKQnDi0Oiid54R/RKx+rVEG181O4sAKqTzP/D5tAosxT5/DzgoFr4U7FgnaHabT1B9dPpks02QfCgWfvyq7UwxStkuwcl/DFrkWFkH/nH/b5GkrAPUEclQsnD5WGanxrTxSuB7GlWD3d4ngq7TobJz1Wpt6vscJ4SCWpDffKKaLUJxNJiw8vK7cEdGyDZSvqKuLfmzJnyNRZqtblRfCviHUYjnZp+gBvcW2LrstavyxJWTAbr22SNr1CEGJaHmlQ602U/pCDRLG1R3EJT68yn6Z2dCMGeVUEYIYhUtl2barjzs9ZOI4EVAWZT9tY1ZByInq9HdVDs5HAzvTrG2wpEh9TdSk7oah7sDrBpjMBiXa6SH0cBbxvPhWrW72UEb0aFNTy+m9o/tmDCkUBtARNWbjEdFVzNexxvKe9jGHPRnbFnYWn6gZ+//N4EdFCqm0ztIcQANWNO6rDvJyQ3rQBFy3JuYEwg9MY/7VswUkbktHmfF0+a4nF5TPklfH6+6nZQyCD5YR0PSZOa/5ZEyEFG+Uzzg7Ixa2Yg/vP8PCspLSVIGl/LGsn1YSGEhZzgKSyeIVFJkVJ28Z/01Cl/2ESnovZg+B5Svte0BBqVQ8WZVQI036evTfGIUBsVusV0Dbp40AUAGO70q6VmqPOSf
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: argocd
    type: Opaque
