---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: adguard
spec:
  encryptedData:
    api-token: AgAwLirZMtxojP09ClUvQil9nqpJ602+PZkms7K17zqZrgHxiCJi6JdMTIDVfG+0LXhK3htyPRviKrRKkLGASxX7L3s7WhCsernGEf6cvR1VZtGsfKYJAbMJDvQirtGJ9Bs3svbJslO1jyPhYm8BsJXCz7k/R1U6WowztzgcaSSCdiDY52Mxv37/6aQI71KjcTbXdbdgbzmgxOG7/v0nKKHiaYJ934Qyh/O/3IYRtXhNXA/YQlgtLPxPWr4TNYE0Hxt2U8Xn5OdYPaXoiAKVEJX4h23pdIuBczZWDvJRdAyG+aELZDtr9oWYTt9ePpWhBSOKY2vYYy1ymy/c9U3wqSGh88/pSO5g9Rq5RSixzP8ZCBPNerfjrahRyTCBpByfMKrIVt2k5FqlNpGH0+czezmrIPMOzkorA575S6zZAA0LNgtguCLjMjud42dWgSab2q0Akdh8+aahZngDvDeGf3Q+sjM1ojllUkVzynT9UizAUndSvxkPiak7P7+JYaRDk562x0mOSqXqky9bxooC98gwQbJpXmNiuGSajxvycOzo2BHAyzUeal1oA/aQvyO9XRlvTbXNJahdggNIDcAdqkSpb/Nt08Vy0u/DfECb2moqK3y0BqqytlQlE6gxxV9xHPtv64fVZMNla7v5k0L7gSB/2YW3gqqbbanKAIrIcm06w7WWhrt7cBWYYWDIVFEXhiKlTcRa1oRt1M1uP1H6Iq0EIqPZMsjvVXig+f04es3/SOvgGh4L9do8
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: adguard
    type: Opaque
