---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: adguard
spec:
  encryptedData:
    api-token: AgCRXO1msV1tpXzI4Ren2pnYQwO+uPHBjd8ojtZmCGXuWLEbK8ApOSzH9YXlRla3GIeW/6k53YimcMRxlvFyriFBZvy5DrzTjYNPNhiiPQxb0KS1ErHCCSGYfOwpy685Tv+3lMndY6sZ1BOYKQusVI0lSYLNsKyTiFE6yD0s/dZAGoS9gCTPevnEitXbu2tMjrZlshiGjQy8yd61LSqAa0NI7wBgNOCTf9M3CNQGj2fJWUVNn/3Uo3gptTuOFTB0mi2XIf6CWiG+HNKt9DvwAUfhV8LP+Is9R3Qb8rx5RZgX/0vmlto1cWb/fiKDrMstPAWbFqELx9z/twgO+MYd6AoXIGJVCR1IgrCDSxx5Kju2g8CkqhGftftDwsqjOAMC+8hyDZMcPkqb4MzkpfBLwxVH6bw4QaZanTB28qeSrFqkITj7Sljv4qQQCFiOIS9eY5C8NiVpNj/7zZXrQBlyEVjBuoL+Tj65QOOBC14p1LTKUApm4PAY2NZanYqfpEUKi26FVzf4QKDuaDuieLnMWeMXt2w2TYmDWd1sdjq7dolaO6qtGEXB7DV1mh/Vn4Z6aUPAMpc/h6VG73V9AjTaD0s0OdGZYghp3mAc8Dly9bVepIPNinC2z0XO1etahBRGPNhGmXliutsYoONTprKty5I+v0to2H8MV4CTzSzPcZcaqdUU/byofwgjmT7IErMJBYnTeLxL7Tk9OiV4Lvwrjib+53PGhTkyk5yu7uNiJlIpZHsaiVma1evr
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: adguard
    type: Opaque
