apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng-redis
  template:
    metadata:
      labels:
        app: searxng-redis
    spec:
      containers:
      - name: searxng-redis
        image: redis:latest
        ports:
        - containerPort: 6379
