apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-postgres-volume
  namespace: vaultwarden
  labels:
    type: local
    app: postgres
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/gluster/global/vaultwarden/db
