apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: portainer
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://portainer.github.io/k8s/
    chart: portainer
    targetRevision: '*'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

