apiVersion: apps/v1
kind: Deployment
metadata:
  name: ha-connectlife-addon
  namespace: ha-connectlife-addon
  labels:
    app: ha-connectlife-addon
  annotations:
    argocd-image-updater.argoproj.io/image-list: kallewasnowicz/connectlife-api-connector
    argocd-image-updater.argoproj.io/update-strategy: latest
    argocd-image-updater.argoproj.io/tag: edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ha-connectlife-addon
  template:
    metadata:
      labels:
        app: ha-connectlife-addon
    spec:
      containers:
      - name: ha-connectlife-addon
        image: kallewasnowicz/connectlife-api-connector:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: CONNECTLIFE_LOGIN
          value: "kai+connectlife@wnsrt.de"
        - name: CONNECTLIFE_PASSWORD
          value: "QERjklConn++0623@"
        - name: LOG_LEVEL
          value: "info"
        - name: MQTT_HOST
          value: "192.168.178.101"
        - name: MQTT_USER
          value: "homeassistant"
        - name: MQTT_PASSWORD
          value: "homeassistant"
        - name: MQTT_PORT
          value: "1883"
        - name: MQTT_SSL
          value: "false"
        - name: DEVICES_CONFIG
          value: '{"117":{"t_work_mode":["fan only","heat","cool","dry","auto"],"t_fan_speed":{"0":"auto","5":"super low","6":"low","7":"medium","8":"high","9":"super high"},"t_swing_direction":["straight","right","both sides","swing","left"],"t_swing_angle":{"0":"swing","2":"bottom 1/6 ","3":"bottom 2/6","4":"bottom 3/6","5":"top 4/6","6":"top 5/6","7":"top 6/6"}}}'
        command: ["/bin/ash", "-c", "/usr/bin/supervisord -c /home/app/docker-files/supervisord.conf"]
