apiVersion: v1
kind: PersistentVolume
metadata:
  name: searxng-pv
  namespace: searxng
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/gluster/global/searxng
