apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: vaultwarden-pv
