---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: vaultwarden
spec:
  encryptedData:
    api-token: AgBrI8//KLN4mJSsQBxjpQfjGevagvDArG+wmcp0l95Zl2X4OOnI04l8xBIUKizCVpaspjQGkGAHAUu4jcn9870oX36mcheWuMORE1zy/UlvD5TIbZ/xGsHzS+caIqsnjXxAeHVty7i6JDXE/W7Qy1KrNK2OalR3dBrXM+84AkQTzfI213RE/5sOJgy4wCT+sAP092UbwQNkp08pEE9RzIuaMv+TNaGSiLv7Z+dJXbZyUhwraeoh5r+nUOpzucLGa/3x+gJoFKiPtrRhwv667zeli8vYgHwaguZhP4gZtGWhiCmp9DsiOy2scDXs3bm9+qwPmkuSGCjaJgCebbED+Ao2nnFW/yVd81t1htG3sFyPDf60oK/W+5PRftEm3pLcqmgATKA2wJUxHuztOo3/LW8/QDbrco2QQ8HN3VWD8u9zLjZZO7q0BE9EMsHk2IOEAeuu29XkRKaUBPuAuSE6IDk3iURhmPjzRuZkdN84bCtMuaJmUH/TlTIm6Bh4pJmr8IggpUlPlYq6Gs0dQ4f9yYWP1M9G0o1H1z3eKCjP/ILrYNr9fz6KNa3EOn8Pve/gs9pGuVZNGaH/KOE5hZHE24YQ6vvXDGJnqXzEXnkr3Z4qKn4RT+mDSF04t9dpudWIFvY49dw4QPg1yg3jead9yBtBdOO160pHLl5oIIN+NoFUuMRh2uKrBP3HBMitK1mJSuiQIODIm4QYSwVMbc3csJOdc5tD+6OlHcqdeRgu9I7d01N0q+Ghe9A+
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: vaultwarden
    type: Opaque
