apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wnsrt
  namespace: cert-manager
spec:
  secretName: wnsrt
  issuerRef:
    name: wnsrt
    kind: ClusterIssuer
  commonName: '*.wnsrt.de'
  dnsNames:
  #- "wnsrt.de"
  - "*.wnsrt.de"
