apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: wnsrt
  namespace: default
spec:
  acme:
    email: kai+letsencrypt@wnsrt.de
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-wildcard
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
