---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB8FKMFhmCa7jR24SOSUVPC4YMbTI9kuirPSY4mddIjSIqQPherkS0FlZI+54rEbLmxLucR7Ehyi1mq6Ob0G0v7FLD+HASPIpQ3sI1UvbZhEwyyQkUGdtw/nCGFwOC/1DJpm5FVZZKodqbfbdopXksFen9CwArE1vp6J1ou8nbNym0qkSxUCOMdd5JzT7ChvQ0QlPeJON7jFzANdfKDRmBDHmz9JX5BvlpR/f0yt0D6o7HpAj9W9X1fylszyX0J1xYpdAQx1iA6oPJBepwYPJ16EdhOL0ZLVDqTh4jZSmdgk1R/+GTVYpWt3dVTK3i+wWnsxcKnD7wMkTcDvguwnAuEy9DZ02Q5ZHqPYLOhzjTodHVmI4ze6M1WpZEEg1lNds4baQTvujzxEeKY0chs84/AXWgDU9fpmjik8HMUsU+6+VPGrs89fEXHmpfJLXX2lrt/VI+X3XCT4OIPQsidDa1xcRXXar1Bz+OR1gI9aPBJSSssz7W+GLM7Et3xK0RNe5Asen0HDGtiHrXS58/9ZYz5PpKcOx7ZxpU+TWuX08jdGtpdUQhC/5PDRtFS08U1FxPRfr6LihyCRgT9Ew6pN3yjE/LXue5qTz2dajqEXBAfEIdGXTUQff60XK9pdDSJ6FvM7m15L+lG/xvQRseD+ihLdkflBn8zrC8Uhp/U/e1H0NS+BEW5kxnUWHVXDwPFi0LdSfciKGLGg06G/I8YOBz9q941erScJSM60syVC9WKrMXu7q3EG1Js
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
