---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBZXr44/b8jG3C8SBacp251ggFL8n8rYgrF6lrTRg9VW6XQqEakUsh288+N0xK7pkyboMZ4PnmIrr79FdDD8ZHAcWM0v/yH5mAbRAr3wEU1jcrAfdoxdua7qxOrkfvqaHYcwJFE2esbEmLECdOxiZI1M76RF/K1muHyX7aBendu0JficG1Qfq/6JwoCEOAvu2CvnnaWeKIKa625DU2La1QdC2QFjsrIYZ4C2BJnvr/RFfI/Bn9jSi70aCXIOEl2vkhi+Z647qBf20mQlDOZBEKhLnF0Nty0Q74cWCiAZRULbsGkkpZG5nagSliU4ZYIycL5n5kLx11GUrtya+o3Q930jesXuv4Y6p+tc0gixuwNU4IauC/qGOZs2KFWFzuTArwLdMtJgnHdts6+fqfot98tzD8H4uqRmhAnCYcU+1zVsfRK0TvIMtX68c6ltgomenyxIxnvoEslYoEUmhYi8tdK8PWgcxv8lvMfiDk7QhckD6CaGwrrHXV5LBXx41Am3T/CfUwddwKQSlFXGdE4a0abvc37wZ2b0iAjyyu2Zb+wYHy8gBwtPVsXsoTFZE9LTFIfkxymuEm8B3CdPz1r+s3W8kXvYG0pUUkPpmnV3Jxm/7GDxV7QW6Jqe+vt92UV5TsDAUFCeIMQZI0zK8KRQFlxgNaEDlR55/6z7zGbmnpeAam+os/aabQPZc8aZUQYg9dKeKjRARrI2UiSEWFfVVQXoccsF6x791Qe8R6BuHmCOTOiWcxTnmF0
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
