---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAr9fSRK4K+C4x5TKmZmcLfTfIxkSUKAgDQN/y8xwefkk5az6/uTbgux8Kh+e4VdgmLiwAZw4MN3vwjk0LTtx6XUYfdN7WQoZ99PEbAtWz7vmC89XPFR58skApy2bCesQdtUeiKn5Tx8AgD0Nnx1jvz6LVE/FGwkRbx36ICibTO01ki+P2p9zLOqyO6gH9NiYnwlUWPTR3TFY1Zsvm/WMbq5ErIOBR8+8gEHDsA+RXGya8EoLvWJgl6f72ta52y+L14Vr+CVti6IpoDLrfZI5kzy480vkyIxu59YX8xzAo0RkfEt4ubYtMQITFSsAUi877TwddCeo6Y+aeEMDGejA0+eK1cKWrsNAThQ1ad6EqgYcGmGGql9lL4KXiK+WLDqjpJSCAMoNvHIw56KjKu0N2xqmijMEGOB+3U9/Nlt6wRPePAreNorDaqsDhCcgbVDv3xBnhVXeuqCGXMqzwuCK6CziFzKaqru3s/fUeo8CXa1KMzZppUTb7oDwXjVpXhyyxW2cmG3C/OOiyoZtHgquvwtQKSEUrXTCPsV6TSLB7LzcV/gQcrSeCA0SEf82RRdjBKTNkWTeW0UlLyfg5kqIcL35bzOs4zdSL6KqxUBwT696A4K8KaeoTkz5yf7OEoIR9umt5hI7CHqMmbDgjTk8AGsBTGTtutrkZGX057c6Xhq8nNbBDrFFJlL537vjhrTRiwD6n1ynvTC5GZ8f/Urto+ft7PAaikeBrlCnCfsjk7HelQ015SlSAk
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
