---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCJYn3amPNUcCW5uovG7jj0uAj585EBIYF88sQnma+IWzqwqMbhmAxhNbK3d/I3fd4nTgqiFSUZIVvTvLbM3DbADDiisomQcaLO93dVsBhldCrKxoCYvDVSlhwU5mIIjiR9LJ99rYihLkOMgvrmObEb7cojyL6tosItueuPEZRWsrNUm/3scgKVVpZGiukyr+NgdS5iwwZjqoJtHm3BrRIaxIUh/hd67rqfkmBYG/z3t8cmoVfmHkLkCkdZHLOBFyOwafFhrJY/nFy/ROg5EcBKykQvIglkNtRROnRCz8gaJ/4bOpFgiZ/CGX5ttbjz6g8GfadwH1TKJX9hyBdhaMqd69AhYC//AGTEyO49/t45MLms/1zA9DVmqkZzcS3Z2BUc2sF1Tn0eB92IlC5WRe4RmiIi3Z4bRq+Flg3KcoVg3+nPdyo09LvlVLRlhTZ2D4B5nPXIGSjwJvPgkhRjl3vZBcwC98sMUxTyI6Zb8/AfVTAotIsCp92rXyheeC2LGUagkrJqVyMjr58yv3wFcQEHjy409jhQEvedGTyv4JeUovcWYnIw+JvDf3LE7As89W07B07cswfgGazn4HIC4yFyL/O7+VSTntZ9DHBIx8Usx68VHsBSxrhpMQ3U4GCYGvIebGLTNzGxwrSC9seUGeFp4yRmqP37BSSouCVznPzAi8hMHa5mLHLyqS6+5Li10ab7K2nJNf05RNAot59Fi+8JehfSw/a8Gvys8HK5UDBw9X1kDu/Q0N7o
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
