---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAX4+oPy3Jtz8Bp+aqcejXvuY5MQZeP27t8PvCYsKtyJuc5YAlXJuRlh+x5XI6zukfGqG0E7jFNYpf3UjOo2snYYpTn00arna5M8jyl59JS3U93MrxvLt9mfPo9ODAcciag/rJKvcidb00pm2HP/ELtljcBYofmU9ND9ex99RqpGJUpkd1is44sLOEeUZ23kFAFBAlJ++PUcNrjl2zCnOlut+LvxgTTjwef0ZnFKbjmVUr1/53y8naPjLiQ2nunFxIes1niN07GrvS0CUtr9Esc9l38BxLXOuI2aUdeCxpEZtx8geAr4MQlnDIFCSPg0ec/G/F4t5JsbEf758QcpORUaUFzlYJmP9jYzO2AUuM0MXwd4wylHFAEaDXQ7TQvt4Qi3xB1ql0y6yCgdX2JRLB/o+ZlGAPRgGRthWqvPSdGg5BT4Url9ju6tb1ONWbD7wcwIZR7cF+AjODSGY/ybOcnSmqZ/zl+0p1OU6aHm/woxxFknMgBjUwa6BqHFsvESf+366jFtePsP7Tn2walnK1p42lIm0qihTun+DbLIjIUZEldN1HYoo6HM/zxDvZToLU67XIFFEGcnTgYAgFPwbi1LgVsL68qMxSu+DQwnAvIU9ok9tOF7YfE7hs9n4ZCQHbglUUCUfVpMbg49UC05j2fLIHc+QieJKSrQ1eqnvKcGdK7lsJVIQ5re08aFZXc32GQ3HGQ+sil3QN63YwDao9Z16C7zGamaBKvDB0O19hAx1K9jEzPngS5
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
