---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: default
spec:
  encryptedData:
    api-token: AgARQqO53VsJb06OrZ+OIPwVHvlZ2lxTRoC01WYaCpn5lHMqE7okj4k+8qlkaTWAuzaZc/zksRJUOl3heXrV2xBQkPZhlHQfSLjFKgk3lMlhRnY+uzRoGyXrr7MFE7jJgbwoS9z5bEDuSqEzKLZj/Vvpp5up0+QcRWeouef5eoNn4kGhy2J2kCyaKpcqqANzq5Zjr7dGxHOz8anwJbjabTgLJxB1Ac1P0Cjk7NhFEJpo8ZtDi6w5pxIcy8g/AGn+Un3tZqwtaYGY3ltgLlpHlFaBdao9itI+/kfzCtZbYN35FViofcl1FwY2zAe4yFjVJbhAY0E54VpcsxBAqvCdn7DZmf8JhNhY9Lo/iGFkEbzsISez+MduIMy40RcEjpRxUx6CiyjpTqDR4poUomM6C9dt0Yf03OpzNNBiXvXmNuOLl+DJLefBkCb2+Whrwkx78QqbGpeDDlqZwu21rFCHtBlUW82Df+J0fkyN4+B7BFYh1guOMsbQMhAb3LEU32xZw2NAo2DibcDcQ8t6c5O4UCBQWmTGqw6NWhEJF/AHY01zuYqCPuAXzr5fopca4Jcyk5zVg/yBEs/bfoHE0alJ4qU/EzbiQdEeuyHd00sC+shgmrhJcDs1hJ03nT7KxLgIrwh+oKeAazlv4jDF3llGf8LiiL90kkYTvDZ7Jq4G6dNUuaplym9HUPaQH0jjZSCsm0DEG/l/2ABnXGCixin7O/CKhAyQogXTnidAlhxv+VimHJ6r5TDr+IcW
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: default
    type: Opaque
